# Generated by Django 6.0.5 on 2026-05-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('contact', models.CharField(max_length=200, verbose_name='Телефон / Email')),
                ('subject', models.CharField(choices=[('wholesale', 'Оптовый запрос'), ('logistics', 'Логистическая поддержка'), ('catalog', 'Технический каталог')], default='wholesale', max_length=20, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработана')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
