# Generated by Django 6.0.5 on 2026-05-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='contact',
            field=models.CharField(max_length=200, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='subject',
            field=models.CharField(blank=True, choices=[('wholesale', 'Оптовый запрос'), ('logistics', 'Логистическая поддержка'), ('catalog', 'Технический каталог')], default='wholesale', max_length=20, verbose_name='Тема'),
        ),
    ]
