# Generated by Django 6.0.5 on 2026-08-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contactrequest_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='consent_given',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных (152-ФЗ)'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP отправителя'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='User-Agent'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='volume',
            field=models.CharField(blank=True, default='', help_text='Например, «50–100 растений» или «на объект 2 га».', max_length=200, verbose_name='Планируемый объём заказа'),
        ),
    ]
