# Generated by Django 6.0.5 on 2026-08-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contactrequest_company_contactrequest_consent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='marketing_consent',
            field=models.BooleanField(default=False, help_text='Клиент явно согласился получать информационные письма.', verbose_name='Согласие на маркетинговую рассылку'),
        ),
    ]
