# Generated by Django 6.0.5 on 2026-05-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('age_years', models.PositiveIntegerField(verbose_name='Возраст (лет)')),
                ('size_cm', models.CharField(help_text='Например, 60-80 или 120', max_length=50, verbose_name='Размер (см)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество (шт)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (₽/шт)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='plants/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
                'ordering': ['name'],
            },
        ),
    ]
