# Generated by Django 6.0.5 on 2026-05-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Если выключено — позиция скрыта от клиентов и в Excel-прайсе.', verbose_name='Показывать в публичном прайс-листе'),
        ),
    ]
