# Generated by Django 6.0.5 on 2026-08-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_plant_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='external_url',
            field=models.URLField(blank=True, default='', help_text='Ссылка на видео, фотогалерею или другой материал. Попадёт в Excel-прайс.', max_length=500, verbose_name='Ссылка на медиа'),
        ),
    ]
