# Generated by Django 6.0.5 on 2026-08-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_plant_external_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Оренбург, Загородное шоссе, 37/2', max_length=300, verbose_name='Адрес питомника')),
                ('map_embed_url', models.URLField(blank=True, default='', help_text='Откройте yandex.ru/maps, найдите точку → «Поделиться» → «Код карты». Скопируйте URL из атрибута src="..." и вставьте сюда.', max_length=1000, verbose_name='URL встраиваемой карты')),
                ('phones', models.TextField(blank=True, default='+7 (912) 846-10-22\n+7 (912) 845-10-22\n+7 (912) 066-38-08', help_text='По одному номеру на строку.', verbose_name='Телефоны')),
                ('email', models.EmailField(blank=True, default='suslova_1983@mail.ru', max_length=254, verbose_name='Email')),
                ('schedule', models.CharField(blank=True, default='Работаем без выходных', max_length=200, verbose_name='Режим работы')),
                ('inn', models.CharField(blank=True, default='565100366000', max_length=20, verbose_name='ИНН')),
                ('footer_about', models.TextField(blank=True, default='Питомник хвойных и декоративных растений. Для дач, садов, парков и городских проектов.', verbose_name='Описание в футере')),
                ('footer_address_title', models.CharField(blank=True, default='Штаб-квартира', max_length=100, verbose_name='Заголовок блока адреса в футере')),
                ('footer_address_note', models.CharField(blank=True, default='Главный кампус питомника', max_length=200, verbose_name='Подпись под адресом в футере')),
                ('copyright_text', models.CharField(blank=True, default='© 2024–2026 Green Decor. ИНН: 565100366000. Все права защищены.', max_length=200, verbose_name='Копирайт')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
