# Generated by Django 6.0.5 on 2026-08-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.TextField(blank=True, default='', help_text='Откройте yandex.ru/maps → «Поделиться» → «Код карты» → «Скопировать» и вставьте полученный HTML-блок целиком (или только URL из src="…").', verbose_name='Код карты'),
        ),
    ]
