# Generated by Django 6.0.5 on 2026-08-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_sitesettings_map_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address_retail',
            field=models.CharField(blank=True, default='', help_text='Оставьте пустым, если розничного питомника нет — блок скроется.', max_length=300, verbose_name='Адрес розничного питомника'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_retail',
            field=models.TextField(blank=True, default='', help_text='Инструкция та же, что и для оптового.', verbose_name='Код карты розничного питомника'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='Оренбург, Загородное шоссе, 37/2', max_length=300, verbose_name='Адрес оптового питомника'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.TextField(blank=True, default='', help_text='Откройте yandex.ru/maps → «Поделиться» → «Код карты» → «Скопировать» и вставьте полученный HTML-блок целиком (или только URL из src="…").', verbose_name='Код карты оптового питомника'),
        ),
    ]
