# Generated by Django 6.0.5 on 2026-08-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_sitesettings_address_retail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='legal_entity',
            field=models.CharField(blank=True, default='ИП Суслова', help_text='Например: «ИП Суслова» или «ООО "Ромашка"». Показывается в футере рядом с ИНН.', max_length=200, verbose_name='Юридическое лицо / ИП'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(blank=True, default='© 2024–2026 Green Decor · ИП Суслова · ИНН: 565100366000. Все права защищены.', max_length=200, verbose_name='Копирайт'),
        ),
    ]
