# Generated by Django 6.0.5 on 2026-08-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_sitesettings_legal_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_kicker',
            field=models.CharField(blank=True, default='Питомник растений', help_text='Тонкая надпись капсом над главным заголовком (обычно 2-3 слова).', max_length=100, verbose_name='Главная — маленькая подпись сверху'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(blank=True, default='Хвойные растения', help_text='Большая надпись на главной. Первая строка отображается обычным цветом.', max_length=200, verbose_name='Главная — заголовок, первая строка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_accent',
            field=models.CharField(blank=True, default='из нашего питомника.', help_text='Продолжение заголовка на новой строке, выделено зелёным курсивом.', max_length=200, verbose_name='Главная — заголовок, вторая строка (зелёный курсив)'),
        ),
    ]
