# Generated by Django 6.0.5 on 2026-08-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_sitesettings_hero_kicker_sitesettings_hero_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='Заполняется автоматически, когда вы напишете боту команду /start в группе. Пока пусто — уведомления не отправляются.', max_length=50, verbose_name='Telegram chat ID'),
        ),
    ]
