# Generated by Django 6.0.5 on 2026-08-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_sitesettings_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(blank=True, default='Green Decor', help_text='Название компании/бренда. Показывается в шапке, футере, заголовках вкладок и во всех правовых текстах. Если поле пусто, будет использоваться «Green Decor».', max_length=100, verbose_name='Название бренда'),
        ),
    ]
